version: '3'  # requires Docker Compose 1.13 or later


services:
  
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'

    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

    # Run this container on a private network for this application.
    # This is necessary for magic Docker DNS to work: other containers
    # also running on this network will see a host name "rabbitmq"
    # (the name of this section) and the internal port 5672, even though
    # that's not explicitly published above.
    networks:
      - network

  randomnumbergenerator:
    build: randomnumbergenerator

    depends_on:
      - rabbitmq

    networks:
      - network

  reader:
    build:
      context: ./DBService/Reader/

    depends_on:
      - rabbitmq
    networks:
      - network

  mysql:
    image: mysql:latest
    volumes:
      - number-info-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: number_info
      MYSQL_USER: liam
      MYSQL_PASSWORD: 123

    expose:
      - 3306
    ports:
      - 3306:3306
    
    networks:
      - network

volumes:
  number-info-data:

networks:
  network: {}