version: '3'  # requires Docker Compose 1.13 or later


services:
  
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'

    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

    # Run this container on a private network for this application.
    # This is necessary for magic Docker DNS to work: other containers
    # also running on this network will see a host name "rabbitmq"
    # (the name of this section) and the internal port 5672, even though
    # that's not explicitly published above.
    networks:
      - network

  randomnumbergenerator:
    build: randomnumbergenerator

    depends_on:
      - rabbitmq

    networks:
      - network

  reader:
    build:
      context: ./DBService/Reader/

    depends_on:
      - rabbitmq
    networks:
      - network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/


networks:
  network: {}